### ISSUE TITLE
Clarification : Availability zone setting

### ISSUE THREAD

**Issue by advissor** [cn-terraform/terraform-aws-ecs-fargate#12]
Hi, 
I notice that in new version of a module 2.0.17, you don't have **availability_zones** 

Does module derive availability zones from the private subnet? 
And how lb_enable_cross_zone_load_balancing corresponds with this? 

Trying to migrate from 2.0.9 version to 2.0.17

BRs,
Vlad

**Comment by jnonino** [comment]
Hi, this modules creates a Load Balancer, an ECS Task Definition and an ECS Service. For that purpose you only need passing subnets IDs which I divide into private and public. You will need to consider availability zones when you create the subnets, for example using this [networking module](https://registry.terraform.io/modules/cn-terraform/networking/aws).

lb_enable_cross_zone_load_balancing indicates to the load balancer that it can redirect traffic to targets on any availability zone. If the subnets you provide are in different availability zones you'll need to enable this.

Hope that helps!!

**Comment by advissor** [comment]
Hi @jnonino thanks a lot!
This answers my question
