### ISSUE TITLE
Changing type of LB from internet-facing to internal results in DuplicateLoadBalancerNam error

### ISSUE THREAD

**Issue by advissor** [cn-terraform/terraform-aws-ecs-fargate#13]
When trying to modify the type of LB from internet-facing to internal, step creating a new LB new lb fails

Error: Error creating application Load Balancer: DuplicateLoadBalancerName: A load balancer with the same name "xxxxx-lb' exists, but with different settings
    status code: 400

So we had to remove it manually via console 

Looks like it tries to create an LB too fast before destruction is complete

**Comment by jnonino** [comment]
Can you try in version [2.0.22](https://registry.terraform.io/modules/cn-terraform/ecs-fargate/aws/2.0.22)
Please reopen this issue if you continue experiencing problems.
