### ISSUE TITLE
Alarm on low cpu after cluster creation 

### ISSUE THREAD

**Issue by advissor** [cn-terraform/terraform-aws-ecs-fargate#15]
There is a bug after creation of a cluster -> alarm is always triggered (low cpu)

1. There should be a way to define alarms on module input level
2. Or way to disable them 
3. Way to control this better

As alarms are used extensively for autoscaling inside fargate, this looks important.

**Comment by jnonino** [comment]
Hi, I'm closing this issue as it has been a long time without new reports. If you find this is still happening, please reopen.
