### ISSUE TITLE
Version 2.0.9 : 

### ISSUE THREAD

**Issue by advissor** [cn-terraform/terraform-aws-ecs-fargate#16]
version             = "2.0.9"

profile             = "xxxxxxx"
region              = "us-east-1"

When trying to comment out the section with the module, the following error is shown. 

 Provider configuration not present

To work with
module.ecs-fargate.module.ecs-fargate-service.aws_cloudwatch_metric_alarm.cpu_high
its original provider configuration at
module.ecs-fargate.module.ecs-fargate-service.provider.aws is required, but it
has been removed. This occurs when a provider configuration is removed while
objects created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.ecs-fargate.module.ecs-fargate-service.aws_cloudwatch_metric_alarm.cpu_high,
after which you can remove the provider configuration again.

**Comment by jnonino** [comment]
Is this still happening for you on newer versions?

**Comment by jnonino** [comment]
Can you try in version [2.0.22](https://registry.terraform.io/modules/cn-terraform/ecs-fargate/aws/2.0.22)
Please close the issue if it is resolved.
Thanks

**Comment by MatthiasVervaet** [comment]
I fixed this by replacing the provider manually:
terraform state replace-provider -auto-approve 'registry.terraform.io/-/aws' 'registry.terraform.io/hashicorp/aws'

**Comment by jnonino** [comment]
Yes, terraform changed the providers location.
Let me know if you have any more issues.
Thanks
