### ISSUE TITLE
Autoscaling role changing on every apply

### ISSUE THREAD

**Issue by advissor** [cn-terraform/terraform-aws-ecs-fargate#19]
Fargate module version : "2.0.17" 
ECS service sub module verion in maintif version = "2.0.4"

**Issues :** 
1)  Autoscaling role changing on every apply
I found very similar thing in https://github.com/cn-terraform/terraform-aws-ecs-fargate-service/issues/14

2) The Scaleup policy is ok. Scaledown policy always in alarm. In top, it " Fails to execute on policy.....arn" the scale down action

So ECS cluster grows, but can't shrink

**Comment by jnonino** [comment]
Hi, I'm closing this issue as it has been a long time without new reports. If you find this is still happening, please reopen.
