### ISSUE TITLE
Add start_timeout support

### ISSUE THREAD

**Issue by atoledo-cit** [cn-terraform/terraform-aws-ecs-fargate#5]
Would it be possible to add start_timeout support? Is there a reason for not having it as an input?
Thanks

**Comment by jnonino** [comment]
I am using another Terraform module to automatically generate the container definition json. The thing is that that module does not include that variable. I fill a requests on their site to include it. In the mean time I will work on a workaround to solve your issue.

**Comment by jnonino** [comment]
Fixed in version 2.0.6.

Let me know how it goes.
