### ISSUE TITLE
NoCredentialProviders: no valid providers in chain. Deprecated.

### ISSUE THREAD

**Issue by ibuchh** [cn-terraform/terraform-aws-ecs-fargate#6]
I am trying to use your "jnonino/ecs-fargate/aws" module with all default settings but as I try terraform plan, I get the following error:

============

Error: error validating provider credentials: error calling sts:GetCallerIdentity: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

  on .terraform/modules/networking/jnonino-terraform-aws-networking-5cb82ad/main.tf line 4, in provider "aws":
   4: provider "aws" {

=============
Can you help.

**Comment by jnonino** [comment]
Hi, how are you? Can you try with new version [2.0.8](https://registry.terraform.io/modules/cn-terraform/ecs-fargate/aws/2.0.8)

Please close the issue if it works for you.
