### ISSUE TITLE
Unable to use this module with firelens 

### ISSUE THREAD

**Issue by typhoonese** [cn-terraform/terraform-aws-ecs-fargate#69]
When attempting to use firelens with this module, I get the following error: `ClientException: When awsfirelens log driver is specified in log configuration, a firelens configuration object must be configured in one of the containers.` How can we go around this? 

It seems that firelens should be defined in the same container definition as the other container created with this module. However, I don't see any input options that enable this. Could you please help? It'd be much appreciated!

**Comment by adeeshaek** [comment]
Just chiming in to add that I also ran into this issue. To generalize it a bit further, it appears that this module does not support the use of any kind of sidecar containers.

**Comment by JaredDarling** [comment]
I have an implementation I'm working on now that will allow for sidecars. I have tested it to create datadag and fluent-bit agents and it seems to be working, but I have one final detail of connectivity to datadog to confirm before I call it tested and ready.

**Comment by jnonino** [comment]
Hi @typhoonese, @adeeshaek thank you for reaching out about this. I will work on this as soon as I can. In the meantime, if you have a solution like @JaredDarling, please do not hesitate to submit a PR, I will review it and merge it ASAP so you can use straight away.

**Comment by JaredDarling** [comment]
Fixed by #107
