### ISSUE TITLE
Broken reference of variables

### ISSUE THREAD

**Issue by mehulu** [cn-terraform/terraform-aws-ecs-fargate#7]
I am getting following errors upon following instructions and module as is with out any structural changes (just filled in values required)
Error: Missing required argument

  on main.tf line 14, in module "ecs-fargate":
  14:   module "ecs-fargate" {  

The argument "ecs_cluster_name" is required, but no definition was found.

Error: Missing required argument

  on main.tf line 14, in module "ecs-fargate":
  14:   module "ecs-fargate" {  

The argument "subnets" is required, but no definition was found.

Error: Missing required argument

  on main.tf line 14, in module "ecs-fargate":
  14:   module "ecs-fargate" {  

The argument "task_definition_arn" is required, but no definition was found.

Error: Missing required argument

  on main.tf line 14, in module "ecs-fargate":
  14:   module "ecs-fargate" {  

The argument "ecs_cluster_arn" is required, but no definition was found.

**Comment by jnonino** [comment]
Hi, how are you? Can you try with new version [2.0.8](https://registry.terraform.io/modules/cn-terraform/ecs-fargate/aws/2.0.8)

Please close the issue if it works for you.
