### ISSUE TITLE
Changing submodule variables

### ISSUE THREAD

**Issue by advissor** [cn-terraform/terraform-aws-ecs-fargate#8]
Hi, 

I've been using the module and everything bootstraps like a charm out of the box. 
Though, I have difficulties settings some of the related submodule settings.

Do you have any examples of changing **lb_target_group** "deregistration delay" or LB timeout values from inside your top module implementation?

And in general, how do you advise to alter the related module features which are not available as input?

Thanks and Regards,
Vlad

**Comment by jnonino** [comment]
Hi, I'll start working on that today and let you know as soon as I have it done.

**Comment by advissor** [comment]
Hi, 
Any intermediate results or ideas on how to achieve this goal you can share ? :)

**Comment by jnonino** [comment]
I have created a new version of the module. It has a lot of extra variables. Please test it and let me know if that works for you. New version: [2.0.11](https://registry.terraform.io/modules/cn-terraform/ecs-fargate/aws/2.0.11)

**Comment by advissor** [comment]
Thanks a lot @jnonino ! Will start testing it and will let you know how it goes :)

**Comment by jnonino** [comment]
Im made some extra corrections to the module on a new version.

**Comment by jnonino** [comment]
module "sonar" {
  source  = "cn-terraform/sonarqube/aws"
  version = "2.0.7"
 
  name_preffix        = var.name_preffix
  profile             = var.profile
  region              = var.region
  vpc_id              = module.networking.vpc_id
  availability_zones  = module.networking.availability_zones
  public_subnets_ids  = module.networking.public_subnets_ids
  private_subnets_ids = module.networking.private_subnets_ids
}

**Comment by advissor** [comment]
@jnonino i see some options missing also like log configuration
Can this be added ? 

log_configuration = {
 logDriver = "awslogs"
                    options = {
                    awslogs-group = "xxxxxxx"
                    awslogs-region = "xxxxxxx"
                    awslogs-stream-prefix = "xxxxxxx"
                    }
                    secretOptions = []
}

I used to pass it like this in version 2.09
Is it still configurable?

**Comment by jnonino** [comment]
Added in version [2.0.13](https://registry.terraform.io/modules/cn-terraform/ecs-fargate/aws/2.0.13). Everything else is working without issues?
